// ! Do not edit this file directly, use npm run router instead
import { Suspense, lazy } from 'react'
import { BrowserRouter, Outlet, Route, Routes } from 'react-router'

import AppLayout from '~app/layout'
import App from '~app/page'

import Loading from '~components/common/Loading'
import NotFound from '~components/common/NotFound'

const DashSubRouter = lazy(() => import('~router/subRouters/DashSubRouter'))
const AuthenticationSubRouter = lazy(() => import('~router/subRouters/AuthenticationSubRouter'))
const SignoutSubRouter = lazy(() => import('~router/subRouters/SignoutSubRouter'))
const SupportSubRouter = lazy(() => import('~router/subRouters/SupportSubRouter'))
const LegalSubRouter = lazy(() => import('~router/subRouters/LegalSubRouter'))

function Router() {
  return (
    <BrowserRouter>
      <Suspense fallback={<Loading source="RouterRoot" />}>
        <Routes>
          <Route
            path="/"
            element={(
              <AppLayout>
                <Outlet />
              </AppLayout>
            )}
          >
            <Route
              index
              element={<App />}
            />
            <Route
              path="-/*"
              element={(
                <Suspense fallback={<Loading source="Router Dash" />}>
                  <DashSubRouter />
                </Suspense>
              )}
            />
            <Route
              path="authentication/*"
              element={(
                <Suspense fallback={<Loading source="Router Authentication" />}>
                  <AuthenticationSubRouter />
                </Suspense>
              )}
            />
            <Route
              path="signout/*"
              element={(
                <Suspense fallback={<Loading source="Router Signout" />}>
                  <SignoutSubRouter />
                </Suspense>
              )}
            />
            <Route
              path="support/*"
              element={(
                <Suspense fallback={<Loading source="Router Support" />}>
                  <SupportSubRouter />
                </Suspense>
              )}
            />
            <Route
              path="legal/*"
              element={(
                <Suspense fallback={<Loading source="Router Legal" />}>
                  <LegalSubRouter />
                </Suspense>
              )}
            />
            <Route
              path="*"
              element={<NotFound />}
            />
          </Route>
        </Routes>
      </Suspense>
    </BrowserRouter>
  )
}

export default Router
