// ! Do not edit this file directly, use npm run router instead

import { Outlet, Route, Routes } from 'react-router'

import AdministratorLayout from '~app/-.../administrator.../layout'
import Administrator from '~app/-.../administrator.../page'
import ProjectsLayout from '~app/-.../administrator.../projects/layout'
import Projects from '~app/-.../administrator.../projects/page'
import UsersLayout from '~app/-.../administrator.../users/layout'
import Users from '~app/-.../administrator.../users/page'

import NotFound from '~components/common/NotFound'

function AdministratorSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={(
          <AdministratorLayout>
            <Outlet />
          </AdministratorLayout>
        )}
      >
        <Route
          index
          element={<Administrator />}
        />
        <Route
          path="projects"
          element={(
            <ProjectsLayout>
              <Outlet />
            </ProjectsLayout>
          )}
        >
          <Route
            index
            element={<Projects />}
          />
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="users"
          element={(
            <UsersLayout>
              <Outlet />
            </UsersLayout>
          )}
        >
          <Route
            index
            element={<Users />}
          />
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default AdministratorSubRouter
