// ! Do not edit this file directly, use npm run router instead
import { Suspense, lazy } from 'react'
import { Outlet, Route, Routes } from 'react-router'

import DashLayout from '~app/-.../layout'
import OnboardingLayout from '~app/-.../onboarding/layout'
import Onboarding from '~app/-.../onboarding/page'
import Dash from '~app/-.../page'
import DirectoriesLayout from '~app/-.../projects/[projectId]/directories/layout'
import Directories from '~app/-.../projects/[projectId]/directories/page'
import ProjectId from '~app/-.../projects/[projectId]/page'

import Loading from '~components/common/Loading'
import NotFound from '~components/common/NotFound'

const AdministratorSubRouter = lazy(() => import('~router/subRouters/AdministratorSubRouter'))

function DashSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={(
          <DashLayout>
            <Outlet />
          </DashLayout>
        )}
      >
        <Route
          index
          element={<Dash />}
        />
        <Route
          path="administrator/*"
          element={(
            <Suspense fallback={<Loading source="Router Administrator" />}>
              <AdministratorSubRouter />
            </Suspense>
          )}
        />
        <Route
          path="projects"
          element={<Outlet />}
        >
          <Route
            index
            element={<NotFound />}
          />
          <Route
            path=":projectId"
            element={<Outlet />}
          >
            <Route
              index
              element={<ProjectId />}
            />
            <Route
              path="directories"
              element={(
                <DirectoriesLayout>
                  <Outlet />
                </DirectoriesLayout>
              )}
            >
              <Route
                index
                element={<Directories />}
              />
              <Route
                path="*"
                element={<NotFound />}
              />
            </Route>
            <Route
              path="*"
              element={<NotFound />}
            />
          </Route>
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="onboarding"
          element={(
            <OnboardingLayout>
              <Outlet />
            </OnboardingLayout>
          )}
        >
          <Route
            index
            element={<Onboarding />}
          />
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default DashSubRouter
