import type { DirectoryRequirementType } from 'launchhero-core'

export const IMAGE_UPLOAD_MAX_SIZE_MB = 10

export const labels: Record<DirectoryRequirementType, string> = {
  url: 'Website',
  name: 'Name',
  punchline: 'Punchline',
  description: 'Description',
  icon: 'Icon',
  logo: 'Logo',
  screenshot: 'Screenshots',
  country: 'Country',
  video: 'Video',
  tags: 'Tags',
  'business-model': 'Business Model',
  demo: 'Demo',
  'first-comment': 'First Comment',
  'product-shoutouts': 'Product Shoutouts',
  x: 'X',
  instagram: 'Instagram',
  linkedin: 'LinkedIn',
  facebook: 'Facebook',
  github: 'GitHub',
  dribbble: 'Dribbble',
  youtube: 'YouTube',
  portfolio: 'Portfolio',
  'team-emails': 'Team Emails',
  'is-maker': 'Are you a maker?',
  'launch-date': 'Launch Date',
  funding: 'Funding',
  'promo-code': 'Promo Code',
  platform: 'Platform',
  'production-status': 'Production Status',
  market: 'Market',
}

export const descriptions: Record<DirectoryRequirementType, string> = {
  url: 'The main URL of your product',
  name: 'The name of your product',
  punchline: 'A short, catchy phrase that summarizes your product',
  description: 'A detailed description of your product, its features, and benefits',
  icon: 'A small icon representing your product. Preferably square.',
  logo: 'Preferably square with a transparent background.',
  screenshot: `Showcasing your product's interface or key features. Try to get at least 3. Max ${IMAGE_UPLOAD_MAX_SIZE_MB}MB.`,
  country: 'The country where your business is based',
  video: 'A promotional or demo video of your product (e.g. YouTube link)',
  tags: 'Relevant tags to categorize your product (e.g. AI, SaaS, Productivity)',
  'business-model': 'How your product makes money (e.g. Free, Freemium, Paid)',
  demo: 'A link to a demo or trial of your product',
  'first-comment': 'Your first comment or post about the product launch',
  'product-shoutouts': 'Any shoutouts to tools that you used to build your product',
  x: 'Your product\'s presence on X or your personal profile link',
  instagram: 'Your product\'s or your Instagram profile link',
  linkedin: 'Your product\'s LinkedIn page link or your personal profile link',
  facebook: 'Your product\'s Facebook page link',
  github: 'Your product\'s GitHub repository link or your GitHub profile (for open-source projects)',
  dribbble: 'Your product\'s Dribbble profile link (for design-focused products)',
  youtube: 'Your product\'s YouTube channel link',
  portfolio: 'A link to your personal or company portfolio showcasing your work',
  'team-emails': 'Email addresses of your team members (comma-separated)',
  'is-maker': 'Indicate if you are one of the makers of the product',
  'launch-date': 'The date you want your product to launch. Should be in the future.',
  funding: 'Details about your funding status',
  'promo-code': 'Any promotional codes available for your product launch',
  platform: 'The platforms your product is available on',
  'production-status': 'Whether your product is live, in construction or in stealth mode',
  market: 'The primary market your product serves',
}

export const placeholders: Partial<Record<DirectoryRequirementType, string>> = {
  url: 'https://yourproduct.com',
  name: 'Your product name',
  punchline: 'The best product ever',
  description: 'Describe your product in a few sentences',
  country: 'USA',
  video: 'https://youtube.com/watch?v=xyz',
  tags: 'AI, SaaS, Productivity',
  'business-model': 'Freemium',
  demo: 'https://yourproduct.com/demo',
  'first-comment': 'Write your first comment for the launch...',
  'product-shoutouts': 'Any shoutouts or testimonials...',
  x: 'https://x.com/yourproduct',
  instagram: 'https://instagram.com/yourproduct',
  linkedin: 'https://linkedin.com/company/yourproduct',
  facebook: 'https://facebook.com/yourproduct',
  github: 'https://github.com/yourproduct',
  dribbble: 'https://dribbble.com/yourproduct',
  youtube: 'https://youtube.com/@yourproduct',
  portfolio: 'https://yourportfolio.com',
  'team-emails': 'team@example.com, founder@example.com',
  'is-maker': 'Yes',
  'launch-date': '2025-01-15',
  funding: 'Bootstrapped, Seed, Series A',
  'promo-code': `CODE${new Date().getFullYear()}`,
  platform: 'Web, iOS, Android',
  'production-status': 'Live',
  market: 'Developers, Designers, Startups',
}

export default labels
