import type { Directory } from 'launchhero-core'
import slugify from 'slugify'

const directories: Directory[] = ([
  {
    name: 'Product Hunt',
    description: 'A community-powered launch platform for discovering, voting on, and ranking the newest tech products.',
    url: 'https://producthunt.com',
    submissionUrl: 'https://www.producthunt.com/posts/new',
    imageUrl: '/images/directories/product-hunt.png',
    tags: ['community'],
    isPaid: false,
    requirements: [
      { type: 'url' },
      { type: 'name', max: 40 },
      { type: 'punchline', max: 60 },
      { type: 'x', optional: true },
      { type: 'description', max: 260 },
      { type: 'tags', max: 3, optional: true },
      { type: 'first-comment', max: 500 },
      { type: 'logo', format: 'Recommended size: 240x240 | JPG, PNG, GIF. Max size: 2MB' },
      { type: 'screenshot', recommended: 3 },
      { type: 'video', format: 'YouTube or Loom', optional: true },
      { type: 'interactive-demo', optional: true },
      { type: 'is-maker' },
      { type: 'team-emails', optional: true },
      { type: 'product-shoutouts', optional: true },
      { type: 'business-model' },
      { type: 'promo-code', optional: true, format: 'Offer - Code - Expiration date' },
      { type: 'funding', optional: true },
      { type: 'launch-date' },
    ],
  },
  {
    name: 'Hacker News',
    description: 'A minimalist, community-driven tech news site where user voting determines what\'s visible and drives the discussion.',
    url: 'https://news.ycombinator.com',
    submissionUrl: 'https://news.ycombinator.com/submit',
    imageUrl: '/images/directories/hacker-news.png',
    tags: ['community'],
    isPaid: false,
    requirements: [
      { type: 'name' },
      { type: 'url' },
      { type: 'description', optional: true },
    ],
  },
  {
    name: 'BetaList',
    description: 'A curated directory for discovering upcoming startups and their product launches before they go mainstream.',
    url: 'https://betalist.com',
    submissionUrl: 'https://betalist.com/submissions/new',
    imageUrl: '/images/directories/betalist.png',
    tags: [],
    isPaid: false,
    requirements: [
      { type: 'icon', format: 'PNG, JPG, or GIF, 1MB max' },
      { type: 'logo', format: 'PNG, JPG, or GIF, 1MB max' },
      { type: 'name' },
      { type: 'punchline' },
      { type: 'url' },
      { type: 'description' },
      { type: 'video', optional: true },
      { type: 'tags', optional: true },
      { type: 'promo-code', optional: true },
      { type: 'screenshot', format: 'Ideally a 4:3 ratio' },
    ],
  },
  {
    name: 'PitchWall',
    description: 'A visual wall of startup pitches with quick, community-driven feedback.',
    url: 'https://pitchwall.co',
    submissionUrl: 'https://pitchwall.co/product/submit',
    imageUrl: '/images/directories/pitchwall.png',
    tags: [],
    isPaid: false,
    requirements: [
      { type: 'url' },
      { type: 'name' },
      { type: 'punchline' },
      { type: 'screenshot' },
      { type: 'description' },
      { type: 'logo', optional: true, format: 'min file size 5kB' },
      { type: 'tags', optional: true },
      { type: 'video', optional: true, format: 'YouTube' },
      { type: 'platform', optional: true },
      { type: 'x', optional: true },
      { type: 'linkedin', optional: true },
      { type: 'instagram', optional: true },
      { type: 'facebook', optional: true },
      { type: 'github', optional: true },
      { type: 'youtube', optional: true },
      { type: 'dribbble', optional: true },
      { type: 'portfolio', optional: true },
    ],
  },
  {
    name: 'Joinly',
    description: 'A lean platform for forming and growing communities with effortless setup and real-time collaboration.',
    url: 'https://joinly.xyz',
    submissionUrl: 'https://joinly.xyz/submit-startup',
    imageUrl: '/images/directories/joinly.png',
    tags: [],
    isPaid: false,
    requirements: [
      { type: 'name' },
      { type: 'url' },
      { type: 'punchline', max: 80 },
      { type: 'description', optional: true },
      { type: 'country' },
      { type: 'logo', format: 'Recommended 256 x 256px (aspect ratio 1:1), max file size 200 KB' },
      { type: 'screenshot', max: 3, format: 'Recommended 1024 x 768px (aspect ratio 4:3), max file size 400 KB', optional: true },
    ],
  },
  {
    name: 'Alternative To',
    description: 'A community-curated directory to discover and compare software alternatives.',
    url: 'https://alternativeto.net',
    submissionUrl: null,
    imageUrl: '/images/directories/alternative-to.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Stackshare',
    description: 'A platform to discover and compare the tools behind modern software stacks.',
    url: 'https://stackshare.io',
    submissionUrl: null,
    imageUrl: '/images/directories/stackshare.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'F65',
    description: 'A global one-stop hub for discovering and applying to startup programs, funding, and partnerships.',
    url: 'https://f6s.com',
    submissionUrl: null,
    imageUrl: '/images/directories/f65.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Launched!',
    description: 'A curated hub that highlights fresh product launches along with the stories behind them.',
    url: 'https://launched.io',
    submissionUrl: null,
    imageUrl: '/images/directories/launched.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Robin Good\'s T5',
    description: 'A curated toolbox of essential online tools for digital creators and marketers.',
    url: 'https://tools.robingood.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup Buffer',
    description: 'An ultra-curated hub of practical startup resources and actionable guides.',
    url: 'https://startupbuffer.com',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-buffer.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup Inspire',
    description: 'A concise, curated hub of startup ideas and insights to spark practical action.',
    url: 'https://startupinspire.com',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-inspire.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup Tracker',
    description: 'A data-driven platform that tracks startup funding, milestones, and trends for investors and founders.',
    url: 'https://startuptracker.io',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-tracker.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'NextBigWhat',
    description: 'A concise tech-startup hub delivering founder-focused insights and curated, practical startup news.',
    url: 'https://nextbigwhat.com',
    submissionUrl: null,
    imageUrl: '/images/directories/next-big-what.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SideProjectors',
    description: 'A community-driven directory of side projects with transparent progress and metrics.',
    url: 'https://sideprojectors.com',
    submissionUrl: null,
    imageUrl: '/images/directories/sideprojectors.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Launching Next',
    description: 'A curated directory that spotlights newly launched startups for quick discovery.',
    url: 'https://www.launchingnext.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: '10 Words',
    description: 'A minimalist platform for crafting stories in exactly ten words.',
    url: 'https://10words.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SaaS Hub',
    description: 'A SaaS catalog with real user reviews and side-by-side product comparisons.',
    url: 'https://saashub.com',
    submissionUrl: null,
    imageUrl: '/images/directories/saashub.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Sidebar.io',
    description: 'A clean, daily five-link roundup of hand-picked, standout web design sites.',
    url: 'https://sidebar.io',
    submissionUrl: null,
    imageUrl: '/images/directories/sidebario.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
] satisfies Omit<Directory, 'id'>[]).map(directory => ({
  id: slugify(directory.url.split('://')[1]),
  ...directory,
}))

export default directories
