import type { Directory } from 'launchhero-core'
import slugify from 'slugify'

const directories: Directory[] = ([
  {
    name: 'Product Hunt',
    description: 'A community-powered launch platform for discovering, voting on, and ranking the newest tech products.',
    url: 'https://producthunt.com',
    submissionUrl: 'https://www.producthunt.com/posts/new',
    imageUrl: '/images/directories/product-hunt.png',
    tags: ['community'],
    isPaid: false,
    requirements: [
      { type: 'url' },
      { type: 'name', max: 40 },
      { type: 'punchline', max: 60 },
      { type: 'x', optional: true },
      { type: 'description', max: 260 },
      { type: 'tags', max: 3, optional: true },
      { type: 'first-comment', max: 500 },
      { type: 'logo', format: 'Recommended size: 240x240 | JPG, PNG, GIF. Max size: 2MB' },
      { type: 'screenshot', recommended: 3 },
      { type: 'video', format: 'YouTube or Loom', optional: true },
      { type: 'demo', optional: true },
      { type: 'is-maker' },
      { type: 'team-emails', optional: true },
      { type: 'product-shoutouts', optional: true },
      { type: 'business-model' },
      { type: 'promo-code', optional: true, format: 'Offer - Code - Expiration date' },
      { type: 'funding', optional: true },
      { type: 'launch-date' },
    ],
  },
  {
    name: 'Hacker News',
    description: 'A minimalist, community-driven tech news site where user voting determines what\'s visible and drives the discussion.',
    url: 'https://news.ycombinator.com',
    submissionUrl: 'https://news.ycombinator.com/submit',
    imageUrl: '/images/directories/hacker-news.png',
    tags: ['community'],
    isPaid: false,
    requirements: [
      { type: 'name' },
      { type: 'url' },
      { type: 'description', optional: true },
    ],
  },
  {
    name: 'BetaList',
    description: 'A curated directory for discovering upcoming startups and their product launches before they go mainstream.',
    url: 'https://betalist.com',
    submissionUrl: 'https://betalist.com/submissions/new',
    imageUrl: '/images/directories/betalist.png',
    tags: [],
    isPaid: false,
    requirements: [
      { type: 'icon', format: 'PNG, JPG, or GIF, 1MB max' },
      { type: 'logo', format: 'PNG, JPG, or GIF, 1MB max' },
      { type: 'name' },
      { type: 'punchline' },
      { type: 'url' },
      { type: 'description' },
      { type: 'video', optional: true },
      { type: 'tags', optional: true },
      { type: 'promo-code', optional: true },
      { type: 'screenshot', format: 'Ideally a 4:3 ratio' },
    ],
  },
  {
    name: 'PitchWall',
    description: 'A visual wall of startup pitches with quick, community-driven feedback.',
    url: 'https://pitchwall.co',
    submissionUrl: 'https://pitchwall.co/product/submit',
    imageUrl: '/images/directories/pitchwall.png',
    tags: [],
    isPaid: false,
    requirements: [
      { type: 'url' },
      { type: 'name' },
      { type: 'punchline' },
      { type: 'screenshot' },
      { type: 'description' },
      { type: 'logo', optional: true, format: 'min file size 5kB' },
      { type: 'tags', optional: true },
      { type: 'video', optional: true, format: 'YouTube' },
      { type: 'platform', optional: true },
      { type: 'x', optional: true },
      { type: 'linkedin', optional: true },
      { type: 'instagram', optional: true },
      { type: 'facebook', optional: true },
      { type: 'github', optional: true },
      { type: 'youtube', optional: true },
      { type: 'dribbble', optional: true },
      { type: 'portfolio', optional: true },
    ],
  },
  {
    name: 'Joinly',
    description: 'A lean platform for forming and growing communities with effortless setup and real-time collaboration.',
    url: 'https://joinly.xyz',
    submissionUrl: 'https://joinly.xyz/submit-startup',
    imageUrl: '/images/directories/joinly.png',
    tags: [],
    isPaid: false,
    requirements: [
      { type: 'name' },
      { type: 'url' },
      { type: 'punchline', max: 80 },
      { type: 'description', optional: true },
      { type: 'country' },
      { type: 'logo', format: 'Recommended 256 x 256px (aspect ratio 1:1), max file size 200 KB' },
      { type: 'screenshot', max: 3, format: 'Recommended 1024 x 768px (aspect ratio 4:3), max file size 400 KB', optional: true },
    ],
  },
  {
    name: 'Alternative To',
    description: 'A community-curated directory to discover and compare software alternatives.',
    url: 'https://alternativeto.net',
    submissionUrl: null,
    imageUrl: '/images/directories/alternative-to.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Stackshare',
    description: 'A platform to discover and compare the tools behind modern software stacks.',
    url: 'https://stackshare.io',
    submissionUrl: null,
    imageUrl: '/images/directories/stackshare.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'F65',
    description: 'A global one-stop hub for discovering and applying to startup programs, funding, and partnerships.',
    url: 'https://f6s.com',
    submissionUrl: null,
    imageUrl: '/images/directories/f65.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Launched!',
    description: 'A curated hub that highlights fresh product launches along with the stories behind them.',
    url: 'https://launched.io',
    submissionUrl: null,
    imageUrl: '/images/directories/launched.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Robin Good\'s T5',
    description: 'A curated toolbox of essential online tools for digital creators and marketers.',
    url: 'https://tools.robingood.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup Buffer',
    description: 'An ultra-curated hub of practical startup resources and actionable guides.',
    url: 'https://startupbuffer.com',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-buffer.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup Inspire',
    description: 'A concise, curated hub of startup ideas and insights to spark practical action.',
    url: 'https://startupinspire.com',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-inspire.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup Tracker',
    description: 'A data-driven platform that tracks startup funding, milestones, and trends for investors and founders.',
    url: 'https://startuptracker.io',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-tracker.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'NextBigWhat',
    description: 'A concise tech-startup hub delivering founder-focused insights and curated, practical startup news.',
    url: 'https://nextbigwhat.com',
    submissionUrl: null,
    imageUrl: '/images/directories/next-big-what.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SideProjectors',
    description: 'A community-driven directory of side projects with transparent progress and metrics.',
    url: 'https://sideprojectors.com',
    submissionUrl: null,
    imageUrl: '/images/directories/sideprojectors.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Launching Next',
    description: 'A curated directory that spotlights newly launched startups for quick discovery.',
    url: 'https://www.launchingnext.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: '10 Words',
    description: 'A minimalist platform for crafting stories in exactly ten words.',
    url: 'https://10words.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SaaS Hub',
    description: 'A SaaS catalog with real user reviews and side-by-side product comparisons.',
    url: 'https://saashub.com',
    submissionUrl: null,
    imageUrl: '/images/directories/saashub.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Sidebar.io',
    description: 'A clean, daily five-link roundup of hand-picked, standout web design sites.',
    url: 'https://sidebar.io',
    submissionUrl: null,
    imageUrl: '/images/directories/sidebario.png',
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup Base',
    description: 'A community-driven hub where makers showcase, discover, and discuss new startups.',
    url: 'https://startupbase.io',
    submissionUrl: 'https://startupbase.io/submissions/start',
    imageUrl: '/images/directories/startupbase.png',
    tags: ['tech-only'],
    isPaid: false,
    requirements: [
      { type: 'name' },
      { type: 'url' },
      { type: 'punchline', max: 120 },
      { type: 'description', min: 160 },
      { type: 'market' },
      { type: 'production-status' },
      { type: 'logo', format: 'Less than 1MB. Recommended size: 512x512px' },
      { type: 'screenshot', min: 1 },
      { type: 'video', optional: true, format: 'YouTube only' },
      { type: 'team-emails' },
    ],
  },
  {
    name: 'Beta Page',
    description: '',
    url: 'https://betapage.co',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SaaS AI Tools',
    description: '',
    url: 'https://saasaitools.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'G2',
    description: '',
    url: 'https://www.g2.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Spectacle',
    description: '',
    url: 'https://spectacle.is',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'StartupLister',
    description: '',
    url: 'https://startuplister.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'The Startup Inc',
    description: '',
    url: 'https://www.thestartupinc.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Toolsalad',
    description: '',
    url: 'https://toolsalad.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Uplabs',
    description: '',
    url: 'https://www.uplabs.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Webwiki',
    description: '',
    url: 'https://www.webwiki.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Promote Project',
    description: '',
    url: 'https://promoteproject.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Profit Hunt',
    description: '',
    url: 'https://profithunt.co',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Beta Candy',
    description: '',
    url: 'https://betacandy.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'EU Startups',
    description: '',
    url: 'https://eu-startups.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startups UK',
    description: '',
    url: 'https://startups.co.uk',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'My Startup Tool',
    description: '',
    url: 'https://mystartuptool.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup Stash',
    description: '',
    url: 'https://startupstash.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AppsThunder',
    description: '',
    url: 'https://appsthunder.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SaaSworthy',
    description: '',
    url: 'https://www.saasworthy.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Apsense',
    description: '',
    url: 'https://www.apsense.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Google Business Profile',
    description: '',
    url: 'https://business.google.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: "There's An AI For That",
    description: '',
    url: 'https://theresanaiforthat.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SourceForge',
    description: '',
    url: 'https://sourceforge.net',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SoftwareSuggest',
    description: '',
    url: 'https://www.softwaresuggest.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'GetApp',
    description: '',
    url: 'https://www.getapp.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SoftwareWorld',
    description: '',
    url: 'https://www.softwareworld.co',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'CloudFindr',
    description: '',
    url: 'https://www.cloudfindr.co',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SoftwareReviews',
    description: '',
    url: 'https://provider.softwarereviews.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'FutureTools',
    description: '',
    url: 'https://www.futuretools.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Nextpedia',
    description: '',
    url: 'https://nextpedia.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'LiveApps',
    description: '',
    url: 'https://liveapps.ai',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Web of AI',
    description: '',
    url: 'https://webofai.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'WaildWorld',
    description: '',
    url: 'https://waildworld.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Top Apps AI',
    description: '',
    url: 'https://topapps.ai',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Free AI Tools Directory',
    description: '',
    url: 'https://free-ai-tools-directory.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AI Registers',
    description: '',
    url: 'https://airegisters.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AI Mojo',
    description: '',
    url: 'https://aimojo.pro',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Powered by AI',
    description: '',
    url: 'https://poweredbyai.app',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'WebAppRater',
    description: '',
    url: 'https://webapprater.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Paggu',
    description: '',
    url: 'https://paggu.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Apps400',
    description: '',
    url: 'https://apps400.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AppsListo',
    description: '',
    url: 'https://appslisto.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AppsMirror',
    description: '',
    url: 'https://appsmirror.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Feedough',
    description: '',
    url: 'https://www.feedough.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Angel',
    description: '',
    url: 'https://angel.co',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Crunchbase',
    description: '',
    url: 'https://www.crunchbase.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Peerlist',
    description: '',
    url: 'https://peerlist.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Bing Places',
    description: '',
    url: 'https://www.bingplaces.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Unboxing Startups',
    description: '',
    url: 'https://unboxingstartups.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Springwise',
    description: '',
    url: 'https://www.springwise.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'All Top Startups',
    description: '',
    url: 'https://alltopstartups.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup Ranking',
    description: '',
    url: 'https://www.startupranking.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AboutUs',
    description: '',
    url: 'https://aboutus.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startups.fyi',
    description: '',
    url: 'https://startups.fyi',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Resource.fyi',
    description: '',
    url: 'https://resource.fyi',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Public APIs',
    description: '',
    url: 'https://public-apis.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Feed My Startup',
    description: '',
    url: 'https://feedmystartup.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Indie Hacker Tools',
    description: '',
    url: 'https://indiehacker.tools',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Insanely Cool Tools',
    description: '',
    url: 'https://insanelycooltools.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Micro Launch',
    description: '',
    url: 'https://microlaunch.net',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Tiny Startups',
    description: '',
    url: 'https://tinystartups.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Business Tool Vault',
    description: '',
    url: 'https://businesstoolvault.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SaaS Surf',
    description: '',
    url: 'https://saassurf.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Yes Ramen',
    description: '',
    url: 'https://yesramen.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Apps and Websites',
    description: '',
    url: 'https://appsandwebsites.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Handpicked Tools',
    description: '',
    url: 'https://handpickedtools.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Find Cool Tools',
    description: '',
    url: 'https://findcooltools.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Prime Indies',
    description: '',
    url: 'https://primeindies.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'All HR Software',
    description: '',
    url: 'https://allhrsoftware.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Once Tools',
    description: '',
    url: 'https://oncetools.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Toools Design',
    description: '',
    url: 'https://toools.design',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Tool Finder',
    description: '',
    url: 'https://toolfinder.co',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Fazier',
    description: '',
    url: 'https://fazier.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'GetByte',
    description: '',
    url: 'https://getbyte.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Early Tools',
    description: '',
    url: 'https://earlytools.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup Spotlight',
    description: '',
    url: 'https://startupspotlight.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Best Free Tools',
    description: '',
    url: 'https://bestfreetools.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Toolfolio',
    description: '',
    url: 'https://toolfolio.co',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Extend Hunt',
    description: '',
    url: 'https://extendhunt.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Hunted Space',
    description: '',
    url: 'https://huntedspace.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Twelve Tools',
    description: '',
    url: 'https://twelvetools.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Launching Today',
    description: '',
    url: 'https://launchingtoday.co',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Feedback Tools',
    description: '',
    url: 'https://feedback.tools',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Submit Your Tools',
    description: '',
    url: 'https://submityourtools.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup Dope',
    description: '',
    url: 'https://startupdope.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Startup 88',
    description: '',
    url: 'https://startup88.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Lazy Hunt',
    description: '',
    url: 'https://lazyhunt.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Web That',
    description: '',
    url: 'https://webthat.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'List.ly',
    description: '',
    url: 'https://list.ly',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Tools Landing Page',
    description: '',
    url: 'https://toolslandingpage.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Find The Tools',
    description: '',
    url: 'https://findthetools.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SaaS PO',
    description: '',
    url: 'https://saaspo.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SaaS Affiliates',
    description: '',
    url: 'https://saasaffiliates.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'SaaS Refs',
    description: '',
    url: 'https://saasrefs.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Best Web Design Tools',
    description: '',
    url: 'https://bestwebdesigntools.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Affiliate For Creators',
    description: '',
    url: 'https://affiliateforcreators.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Disrupt 500',
    description: '',
    url: 'https://disrupt500.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: '100 Apps',
    description: '',
    url: 'https://100apps.co',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Advanced Innovation',
    description: '',
    url: 'https://advancedinnovation.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Afford Hunt',
    description: '',
    url: 'https://affordhunt.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AI Directory',
    description: '',
    url: 'https://aidirectory.org',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AI Marketing Directory',
    description: '',
    url: 'https://aimarketingdirectory.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AI Monstr',
    description: '',
    url: 'https://aimonstr.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AI Tool Mall',
    description: '',
    url: 'https://aitoolmall.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AI Tools Directory',
    description: '',
    url: 'https://aitoolsdirectory.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AI Tools Masters',
    description: '',
    url: 'https://aitoolsmasters.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'AI Wiki Tools',
    description: '',
    url: 'https://aiwikitools.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Any FP',
    description: '',
    url: 'https://anyfp.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'App Rater',
    description: '',
    url: 'https://apprater.net',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Awesome Indie',
    description: '',
    url: 'https://awesomeindie.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Awesome Marketing Websites',
    description: '',
    url: 'https://awesomemarketingwebsites.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Best of AI',
    description: '',
    url: 'https://bestofai.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Browse AI',
    description: '',
    url: 'https://browse.ai',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Capterra',
    description: '',
    url: 'https://www.capterra.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Cloud Findr',
    description: '',
    url: 'https://cloudfindr.co',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Crazy About Startups',
    description: '',
    url: 'https://crazyaboutstartups.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Dev Pages',
    description: '',
    url: 'https://devpages.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Devpost',
    description: '',
    url: 'https://devpost.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Easy Save AI',
    description: '',
    url: 'https://easysaveai.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
  {
    name: 'Ecommerce Stack',
    description: '',
    url: 'https://ecommercestack.co',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    isPaid: false,
    requirements: [],
  },
] satisfies Omit<Directory, 'id' | 'domainAuthority'>[]).map(directory => ({
  id: slugify(directory.url.split('://')[1]),
  ...directory,
  domainAuthority: 0,
}))

export default directories
