import type { Directory } from 'launchhero-core'

export type DirectoryInput = Omit<Directory, 'id' | 'description'>

const directoriesInput: DirectoryInput[] = [
  {
    name: 'Product Hunt',
    url: 'https://producthunt.com',
    submissionUrl: 'https://www.producthunt.com/posts/new',
    imageUrl: '/images/directories/product-hunt.png',
    tags: ['community'],
    requirements: [
      { type: 'url' },
      { type: 'name', max: 40 },
      { type: 'tagline', max: 60 },
      { type: 'x', optionnal: true },
      { type: 'description', max: 260 },
      { type: 'tags', max: 3, optionnal: true },
      { type: 'first-comment', max: 500 },
      { type: 'logo', format: 'Recommended size: 240x240 | JPG, PNG, GIF. Max size: 2MB' },
      { type: 'screenshot', recommended: 3 },
      { type: 'video', format: 'YouTube or Loom', optionnal: true },
      { type: 'interactive-demo', optionnal: true },
      { type: 'did-work-on-product' },
      { type: 'co-creator-emails', optionnal: true },
      { type: 'product-shoutouts', optionnal: true },
      { type: 'business-model' },
      { type: 'promo-code', optionnal: true, format: 'Offer - Code - Expiration date' },
      { type: 'funding', optionnal: true },
    ],
  },
  {
    name: 'Hacker News',
    url: 'https://news.ycombinator.com',
    submissionUrl: null,
    imageUrl: '/images/directories/hacker-news.png',
    tags: ['community'],
    requirements: [],
  },
  {
    name: 'BetaList',
    url: 'https://betalist.com',
    submissionUrl: null,
    imageUrl: '/images/directories/betalist.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'PitchWall',
    url: 'https://pitchwall.co',
    submissionUrl: null,
    imageUrl: '/images/directories/pitchwall.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'Joinly',
    url: 'https://joinly.xyz',
    submissionUrl: null,
    imageUrl: '/images/directories/joinly.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'Alternative To',
    url: 'https://alternativeto.net',
    submissionUrl: null,
    imageUrl: '/images/directories/alternative-to.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'Stackshare',
    url: 'https://stackshare.io',
    submissionUrl: null,
    imageUrl: '/images/directories/stackshare.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'F65',
    url: 'https://f6s.com',
    submissionUrl: null,
    imageUrl: '/images/directories/f65.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'Launched!',
    url: 'https://launched.io',
    submissionUrl: null,
    imageUrl: '/images/directories/launched.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'Robin Good\'s T5',
    url: 'https://tools.robingood.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    requirements: [],
  },
  {
    name: 'Startup Buffer',
    url: 'https://startupbuffer.com',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-buffer.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'Startup Inspire',
    url: 'https://startupinspire.com',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-inspire.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'Startup Tracker',
    url: 'https://startuptracker.io',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-tracker.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'NextBigWhat',
    url: 'https://nextbigwhat.com',
    submissionUrl: null,
    imageUrl: '/images/directories/next-big-what.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'SideProjectors',
    url: 'https://sideprojectors.com',
    submissionUrl: null,
    imageUrl: '/images/directories/sideprojectors.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'Launching Next',
    url: 'https://www.launchingnext.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    requirements: [],
  },
  {
    name: '10 Words',
    url: 'https://10words.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
    requirements: [],
  },
  {
    name: 'SaaS Hub',
    url: 'https://saashub.com',
    submissionUrl: null,
    imageUrl: '/images/directories/saashub.png',
    tags: [],
    requirements: [],
  },
  {
    name: 'Sidebar.io',
    url: 'https://sidebar.io',
    submissionUrl: null,
    imageUrl: '/images/directories/sidebario.png',
    tags: [],
    requirements: [],
  },
]

export default directoriesInput
