import type { Directory } from 'launchhero-core'

export type DirectoryInput = Omit<Directory, 'id' | 'description'>

const directoriesInput: DirectoryInput[] = [
  {
    name: 'Product Hunt',
    url: 'https://producthunt.com',
    submissionUrl: 'https://www.producthunt.com/posts/new',
    imageUrl: '/images/directories/product-hunt.png',
    tags: ['community'],
  },
  {
    name: 'Hacker News',
    url: 'https://news.ycombinator.com',
    submissionUrl: null,
    imageUrl: '/images/directories/hacker-news.png',
    tags: ['community'],
  },
  {
    name: 'BetaList',
    url: 'https://betalist.com',
    submissionUrl: null,
    imageUrl: '/images/directories/betalist.png',
    tags: [],
  },
  {
    name: 'PitchWall',
    url: 'https://pitchwall.co',
    submissionUrl: null,
    imageUrl: '/images/directories/pitchwall.png',
    tags: [],
  },
  {
    name: 'Joinly',
    url: 'https://joinly.xyz',
    submissionUrl: null,
    imageUrl: '/images/directories/joinly.png',
    tags: [],
  },
  {
    name: 'Alternative To',
    url: 'https://alternativeto.net',
    submissionUrl: null,
    imageUrl: '/images/directories/alternative-to.png',
    tags: [],
  },
  {
    name: 'Stackshare',
    url: 'https://stackshare.io',
    submissionUrl: null,
    imageUrl: '/images/directories/stackshare.png',
    tags: [],
  },
  {
    name: 'F65',
    url: 'https://f6s.com',
    submissionUrl: null,
    imageUrl: '/images/directories/f65.png',
    tags: [],
  },
  {
    name: 'Launched!',
    url: 'https://launched.io',
    submissionUrl: null,
    imageUrl: '/images/directories/launched.png',
    tags: [],
  },
  {
    name: 'Robin Good\'s T5',
    url: 'https://tools.robingood.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
  },
  {
    name: 'Startup Buffer',
    url: 'https://startupbuffer.com',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-buffer.png',
    tags: [],
  },
  {
    name: 'Startup Inspire',
    url: 'https://startupinspire.com',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-inspire.png',
    tags: [],
  },
  {
    name: 'Startup Tracker',
    url: 'https://startuptracker.io',
    submissionUrl: null,
    imageUrl: '/images/directories/startup-tracker.png',
    tags: [],
  },
  {
    name: 'NextBigWhat',
    url: 'https://nextbigwhat.com',
    submissionUrl: null,
    imageUrl: '/images/directories/next-big-what.png',
    tags: [],
  },
  {
    name: 'SideProjectors',
    url: 'https://sideprojectors.com',
    submissionUrl: null,
    imageUrl: '/images/directories/sideprojectors.png',
    tags: [],
  },
  {
    name: 'Launching Next',
    url: 'https://www.launchingnext.com',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
  },
  {
    name: '10 Words',
    url: 'https://10words.io',
    submissionUrl: null,
    imageUrl: null,
    tags: [],
  },
  {
    name: 'SaaS Hub',
    url: 'https://saashub.com',
    submissionUrl: null,
    imageUrl: '/images/directories/saashub.png',
    tags: [],
  },
  {
    name: 'Sidebar.io',
    url: 'https://sidebar.io',
    submissionUrl: null,
    imageUrl: '/images/directories/sidebario.png',
    tags: [],
  },
]

export default directoriesInput
